server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-db2iob6gekts73f8jq70-a:5432/kobe_d4au
spring.datasource.username=kobe_d4au
spring.datasource.password=jL2CVACcES8xoLQzstI3gbc3ymlQKPl9
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update